# Generated by Django 2.2 on 2019-12-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserBlog', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
