# Generated by Django 2.2 on 2019-12-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBlog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.SlugField(default=True, max_length=100),
        ),
    ]
