# Generated by Django 2.2 on 2019-12-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserBlog', '0005_auto_20191210_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Slug',
        ),
    ]
