# Generated by Django 2.2 on 2019-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBlog', '0006_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Slug',
            field=models.SlugField(default=True),
        ),
    ]
