# Generated by Django 2.2 on 2019-12-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBlog', '0007_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='file', upload_to='files/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture/%Y/%m/'),
        ),
    ]
