# Generated by Django 2.2 on 2019-12-11 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBlog', '0009_auto_20191211_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 12, 18, 22, 609652)),
        ),
    ]
