# Generated by Django 2.2 on 2019-12-11 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBlog', '0010_auto_20191211_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 15, 41, 13, 703594)),
        ),
    ]
