# Generated by Django 2.2 on 2019-12-11 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBlog', '0011_auto_20191211_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 16, 13, 24, 14708)),
        ),
    ]
